#-------------------------------
# General Site Settings

title: Diegorra
logo: 
#logo: {{ site.baseurl }}/assets/images/favicon.jpg
author: Diego
description: this is my portfolio
email: diegoramonsanchis@gmail.com
phone: +34 601 307 608
address: Madrid, Spain
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Projects, link: '/blog'}
#- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Diego, <br> Welcome to my personal page!

social:
#- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "https://www.instagram.com/diego_rra/"}
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/diego-ram%C3%B3n-sanchis-73590a227/"}
- {icon: "ti-github", link: "https://github.com/Diegorra"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I am Diego an this is my personal page, welcome! I am finishing my last years of college at Universidad Complutense de Madrid and I am studing Computer Science. In these years I have learnt so many things such as programming languajes like Java, Python, C/C++, JavaSrcipt, development of software using diferent architectures like REST or MicroServices, relational databases like SQL, MySQL and non relational databases like MongoDB, and the basics of computer and web security
blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
#team:
#  - title : "Jack Schenziwe"
#    image : "assets/images/team/member-1.png"
#    designation : "Project Manager"
#    
#  - title : "Julias Carlie"
#    image : "assets/images/team/member-2.png"
#    designation : "Web Developer"
    
#  - title : "John Doe"
#    image : "assets/images/team/member-3.png"
#    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Java, color: '#fdb157', value: '90%'}
- {name: C, color: '#9473e6', value: '60%'}
- {name: Python, color: '#bdecf6', value: '80%'}
- {name: C++, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

#experience-title: Experience
#experience:
#- {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
#- {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
#- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Computer Science, date: '2019-now', organization: 'Universidad Complutense de Madrid'}
- {name: Web Development course(HTML & CSS), date: '2018', organization: 'ICAI'}
- {name: App Development couse, date: '2018', organization: 'ICAI'}
- {name: The complete course for web development, date: '2021', organization: 'Udemy'}


#-------------------------------
# Services Section
#services-title: Services
#services:
#- {
#    name: UI Design,
#    icon: ti-palette,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }
#- {
#    name: UX Design,
#    icon: ti-vector,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: true # Add true to select section
#  }
#- {
#    name: Interaction Design,
#    icon: ti-panel,
#    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#    active: # Add true to select section
#  }



#-------------------------------
# Portfolio (Section and Page)



#-------------------------------
# Testimonials Section

#testimonial-items:
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation : "CEO, Funder"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

#client-slider-items:
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: diegoramonsanchis@gmail.com
